version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend/reitera-backend"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      angular:
        patterns:
          - "@angular/*"
