server:
  port: 8080

spring:
  application:
    name: reitera-backend
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

api:
  security:
    jwt:
      expiration-time: 900000
    refresh-token:
      expiration-days: 7

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
