spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
  jpa:
    show-sql: false

api:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  base-url: https://reitera.vercel.app/auth

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
