server:
  port: 8080

spring:
  application:
    name: reitera-backend

  # Configuracion de la Base de Datos PostgreSQL (Docker local)
  datasource:
    url: jdbc:postgresql://localhost:5432/reitera_db
    username: reitera_admin
    password: reitera_password
    driver-class-name: org.postgresql.Driver

  # Configuracion de JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    jwt:
      secret-key: "ReiteraAppSuperSecretKeyForJWTGenerationDoNotShare2026!"
      expiration-time: 86400000