-- ============================================================
-- Reitera — Database Schema Initialization
-- ============================================================
-- Safe to re-run in development: drops ALL objects in the public
-- schema first so stale tables from old schema versions are also
-- removed. Wrapped in a transaction so a mid-script failure rolls
-- back completely — you never end up with a partial schema.
-- Prerequisites: Docker container 'reitera_postgres' running,
-- connected to 'reitera_db' as 'reitera_admin'.
-- ============================================================

BEGIN;

-- Required by seed.sql to generate BCrypt password hashes.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Drop ALL tables in the public schema dynamically.
-- This handles stale tables from previous schema versions that
-- are not listed explicitly, avoiding the "leftover tables" problem.
DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN
        SELECT tablename
        FROM pg_tables
        WHERE schemaname = 'public'
    LOOP
        EXECUTE format('DROP TABLE IF EXISTS %I CASCADE', r.tablename);
    END LOOP;
END $$;


-- 1. ROLES
CREATE TABLE roles (
    id   SERIAL      PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);


-- 2. USERS
CREATE TABLE users (
    id                            UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    username                      VARCHAR(50)  NOT NULL UNIQUE,
    email                         VARCHAR(100) NOT NULL UNIQUE,
    password                      VARCHAR      NOT NULL,
    first_name                    VARCHAR(50)  NOT NULL,
    last_name                     VARCHAR(100) NOT NULL,
    created_at                    TIMESTAMP    DEFAULT NOW(),
    updated_at                    TIMESTAMP    DEFAULT NOW(),
    role_id                       INTEGER      NOT NULL REFERENCES roles(id),
    email_verified                BOOLEAN      NOT NULL DEFAULT FALSE,
    verification_token            VARCHAR(64)  UNIQUE,
    verification_token_expires_at TIMESTAMP,
    password_reset_token            VARCHAR(64)  UNIQUE,
    password_reset_token_expires_at TIMESTAMP,
    avatar_id                       VARCHAR(50)
);


-- 3. CATEGORIES
CREATE TABLE categories (
    id          SERIAL      PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP   DEFAULT NOW()
);


-- 4. DECKS
CREATE TABLE decks (
    id          SERIAL       PRIMARY KEY,
    title       VARCHAR(100) NOT NULL,
    description TEXT,
    owner_id    UUID         NOT NULL REFERENCES users(id),
    author_name VARCHAR(150),
    category_id INTEGER      REFERENCES categories(id),
    created_at  TIMESTAMP    DEFAULT NOW(),
    updated_at  TIMESTAMP    DEFAULT NOW()
);


-- 5. NOTES
-- A note is what the user writes in Markdown. The NoteParser derives one or more cards from it.
-- Explanation lives here (shared across all child cards of this note).
CREATE TABLE notes (
    id          SERIAL       PRIMARY KEY,
    deck_id     INTEGER      NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
    type        VARCHAR(50)  NOT NULL,
    content     TEXT         NOT NULL,
    explanation TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- 6. CARDS
-- Cards are generated by NoteParser from a Note and never edited directly.
-- answer_json uses JSONB; format depends on type: BASIC, BASIC_REVERSE, CLOZE, MULTIPLE_CHOICE.
-- ordinal distinguishes sibling cards within the same note (e.g. the two sides of BASIC_REVERSE).
CREATE TABLE cards (
    id          SERIAL       PRIMARY KEY,
    note_id     INTEGER      NOT NULL REFERENCES notes(id) ON DELETE CASCADE,
    deck_id     INTEGER      NOT NULL REFERENCES decks(id) ON DELETE CASCADE,
    type        VARCHAR(50)  NOT NULL,
    ordinal     SMALLINT     NOT NULL DEFAULT 0,
    question    TEXT         NOT NULL,
    answer_json JSONB        NOT NULL
);


-- 7. STUDY_PROGRESS
-- One row per (user, card) pair. Stores FSRS state variables.
-- States: 0=New, 1=Learning, 2=Review, 3=Relearning.
CREATE TABLE study_progress (
    user_id        UUID             NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_id        INTEGER          NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
    stability      FLOAT8           NOT NULL DEFAULT 0.0,
    difficulty     FLOAT8           NOT NULL DEFAULT 0.0,
    elapsed_days   INTEGER          NOT NULL DEFAULT 0,
    scheduled_days INTEGER          NOT NULL DEFAULT 0,
    reps           INTEGER          NOT NULL DEFAULT 0,
    lapses         INTEGER          NOT NULL DEFAULT 0,
    state          INTEGER          NOT NULL DEFAULT 0,
    last_review    TIMESTAMP,
    next_review    TIMESTAMP,
    PRIMARY KEY (user_id, card_id)
);


-- 8. REVIEW_LOGS
-- Immutable audit ledger. One row per review action. Never updated, only appended.
CREATE TABLE review_logs (
    id             SERIAL  PRIMARY KEY,
    user_id        UUID    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_id        INTEGER NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
    rating         INTEGER NOT NULL,
    elapsed_days   INTEGER NOT NULL,
    scheduled_days INTEGER NOT NULL,
    review_date    TIMESTAMP DEFAULT NOW()
);


-- 9. REFRESH_TOKENS
-- One row per active session. Stores a SHA-256 hash of the raw token (never the token itself).
-- The revoked flag allows explicit logout without deleting the row, preserving the audit trail.
CREATE TABLE refresh_tokens (
    id         SERIAL       PRIMARY KEY,
    token_hash VARCHAR(64)  NOT NULL UNIQUE,
    user_id    UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TIMESTAMP    NOT NULL,
    revoked    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    DEFAULT NOW()
);


-- INDEXES
-- PostgreSQL does not auto-index FK columns. These cover the most frequent query paths.

CREATE INDEX idx_study_progress_user_next_review
    ON study_progress (user_id, next_review);

CREATE INDEX idx_notes_deck_id
    ON notes (deck_id);

CREATE INDEX idx_cards_note_id
    ON cards (note_id);

CREATE INDEX idx_cards_deck_id
    ON cards (deck_id);

CREATE INDEX idx_decks_owner_id
    ON decks (owner_id);

CREATE INDEX idx_review_logs_user_id
    ON review_logs (user_id);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);


COMMIT;
